server {
  listen 80;
  server_name _;

  root /app/public;
  index index.php;

  # Laravel front controller
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  # PHP-FPM
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass users-php:9000;
    fastcgi_read_timeout 60;
  }

  # Security: block hidden files
  location ~ /\. {
    deny all;
  }
  
}