CREATE DATABASE IF NOT EXISTS usersdb;
CREATE DATABASE IF NOT EXISTS nkosi_db;
CREATE DATABASE IF NOT EXISTS dumi_db;
CREATE DATABASE IF NOT EXISTS hlayi_db;
CREATE DATABASE IF NOT EXISTS siya_db;
CREATE DATABASE IF NOT EXISTS bev_db;

CREATE USER IF NOT EXISTS 'nkosi'@'%' IDENTIFIED BY 'NkosiPass123!';
CREATE USER IF NOT EXISTS 'dumi'@'%'  IDENTIFIED BY 'DumiPass123!';
CREATE USER IF NOT EXISTS 'hlayi'@'%' IDENTIFIED BY 'HlayiPass123!';
CREATE USER IF NOT EXISTS 'siya'@'%'  IDENTIFIED BY 'SiyaPass123!';
CREATE USER IF NOT EXISTS 'bev'@'%'   IDENTIFIED BY 'BevPass123!';

GRANT ALL PRIVILEGES ON nkosi_db.* TO 'nkosi'@'%';
GRANT ALL PRIVILEGES ON dumi_db.*  TO 'dumi'@'%';
GRANT ALL PRIVILEGES ON hlayi_db.* TO 'hlayi'@'%';
GRANT ALL PRIVILEGES ON siya_db.*  TO 'siya'@'%';
GRANT ALL PRIVILEGES ON bev_db.*   TO 'bev'@'%';

FLUSH PRIVILEGES;
