services:
  shipment-web:
    image: webdevops/php-nginx:8.4
    container_name: shipment-web
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8088:80"
    volumes:
      - ./app:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_DISPLAY_ERRORS: 1
      PHP_MEMORY_LIMIT: 512M
      PHP_POST_MAX_SIZE: 100M
      PHP_UPLOAD_MAX_FILESIZE: 100M
    depends_on:
      - shipment-mysql
    networks:
      - shipment-net
      - siya-net

  shipment-mysql:
    image: mysql:8.0
    container_name: shipment-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: shipment_lite
      MYSQL_USER: shipment_user
      MYSQL_PASSWORD: shipment_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - shipment_mysql_data:/var/lib/mysql
    networks:
      - shipment-net

  shipment-phpmyadmin:
    image: phpmyadmin:latest
    container_name: shipment-phpmyadmin
    restart: unless-stopped
    ports:
      - "8089:80"
    environment:
      PMA_HOST: shipment-mysql
      PMA_PORT: 3306
    depends_on:
      - shipment-mysql
    networks:
      - shipment-net

volumes:
  shipment_mysql_data:

networks:
  shipment-net:
    driver: bridge

  siya-net:
    external: true
    name: microservices-platform_internal