FROM python:3.11-slim

# Install dependencies
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY main.py .

# Expose port 80 and run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]